### ISSUE TITLE
批量请求超时问题

### ISSUE THREAD

**Issue by xmoney** [bopo/mootdx#21]
client = Quotes.factory(market='std')
    for _ in range(1, 4000):
        data = client.bars(symbol='600547', frequency=9, start=0, offset=200)
        print(data)

Traceback (most recent call last):
  File "test_stock.py", line 81, in <module>
    test()
  File "/home/ubuntu/python_dev/stock/lib/func.py", line 32, in wrapper
    func(*args, **wkargs)
  File "test_stock.py", line 70, in test
    data = client.bars(symbol='600547', frequency=9, start=0, offset=200)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mootdx/quotes.py", line 82, in bars
    with self.client.connect(*self.bestip):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pytdx/base_socket_client.py", line 179, in connect
    self.setup()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pytdx/hq.py", line 46, in setup
    SetupCmd1(self.client).call_api()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pytdx/parser/base.py", line 74, in call_api
    result = self._call_api()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pytdx/parser/base.py", line 101, in _call_api
    head_buf = self.client.recv(self.rsp_header_len)
socket.timeout: timed out

下面代码正常
    api = TdxHq_API()
    with api.connect('47.103.88.146', 7709):
        for _ in range(1, 4000):
            data = api.to_df(api.get_security_bars(9, 1, '600547', 0, 200))
            print(data)

**Comment by bopo** [comment]
先进行测试最优服务器，运行以下命令行：

`mootdx bestip -w -v`

**Comment by xmoney** [comment]
> 先进行测试最优服务器，运行以下命令行：
> 
> `mootdx bestip -w -v`

我就是选择的最优服务器之后再获取数据，或许是封装的某个地方有问题吧，单次调用接口都是好的。

**Comment by bopo** [comment]
可能是服务器连接问题，提示错误是服务器超时
