### ISSUE TITLE
0.6.4版本安装正常，使用时报错

### ISSUE THREAD

**Issue by iam36** [bopo/mootdx#57]
pip install mootdx
Successfully installed mootdx-0.6.4 tqdm-4.48.2

1、运行命令行mootdx报错
mootdx
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\mootdx.exe\__main__.py", line 4, in <module>
  File "c:\anaconda3\lib\site-packages\mootdx\__main__.py", line 9, in <module>
    from mootdx.quotes import Quotes
  File "c:\anaconda3\lib\site-packages\mootdx\quotes.py", line 7, in <module>
    from .contrib.pytdx.hq import TdxHq_API
  File "c:\anaconda3\lib\site-packages\mootdx\contrib\pytdx\hq.py", line 24, in <module>
    from pytdx.parser.get_report_file import GetReportFile
ModuleNotFoundError: No module named 'pytdx.parser.get_report_file'
报错的文件模块都存在

2、运行写入配置文件报错（mootdx bestip -w -v）
报错内容与1点相同

3、导入模块报错
from mootdx.quotes import Quotes  报错 No module named 'pytdx.parser.get_report_file'
或者
from mootdx.reader import Reader 报错  No module named 'pytdx.reader.history_financial_reader'

请问如何解决？

**Comment by iam36** [comment]
居然是因为要自己装pytdx，再去看了requirement才知道。
anyway，就是这个原因。
呵呵
